schema:
  - "server/schema.ts"

documents:
  - "public/**/*.{js,ts,jsx,tsx}"
  - "server/**/*.{js,ts,jsx,tsx}"

extensions:
  endpoints:
    default:
      url: http://localhost:4001/graphql
      headers:
        Authorization: "Bearer ${env:AUTH_TOKEN}"

include:
  - "public/**/*.{js,ts,jsx,tsx}"
  - "server/**/*.{js,ts,jsx,tsx}"

exclude:
  - "node_modules/**"
  - "dist/**"
  - "build/**"